name: Verify Build Workflow
on:
  push:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README*'
      - 'CODE_OF_CONDUCT*'
    branches: [main]
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README*'
      - 'CODE_OF_CONDUCT*'
    branches: [main]

jobs:
  build-verify:
    name: Verify Build
    runs-on: ubuntu-20.04
    if: github.repository_owner == 'Apicurio'
    steps:
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Check Java Version
        run: java -version

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Verify Build
        run: |
          ./mvnw clean install -Dmaven.javadoc.skip=true --no-transfer-progress

      - name: Build Images for Docker.io
        if: github.event_name == 'push'
        run: docker build -f ./Dockerfile -t quay.io/apicurio/apicurio-registry-probe:latest ./

      - name: List All The Images
        if: github.event_name == 'push'
        run: docker images

      - name: Login to Quay.io Registry
        if: github.event_name == 'push'
        run: docker login -u "${{ secrets.QUAY_USERNAME }}" -p "${{ secrets.QUAY_PASSWORD }}" quay.io

      - name: Build Images for Quay.io
        if: github.event_name == 'push'
        run: docker build -f ./Dockerfile -t quay.io/apicurio/apicurio-registry-probe:latest ./

      - name: List All The Images
        if: github.event_name == 'push'
        run: docker images

      - name: Push Images To Quay.io
        if: github.event_name == 'push'
        run: docker push quay.io/apicurio/apicurio-registry-probe:latest

